name: GitHub Actions Demo
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update apt-get
        run: sudo apt update && sudo apt upgrade

      - name: Install packages
        run: sudo apt install python-tk python3-tables \
                  gcc g++ build-essential libncurses-dev \
                  cython libx11-dev git flex automake \
                  libxext-dev libncurses-dev make 


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          source tests/test.sh